### ISSUE TITLE
Ошибка при создании нового подписчика.

### ISSUE THREAD

**Issue by ExpSPB** [Segate-ekb/integration_subsystem#23]
При записи нового подписчика появляется ошибка "Поле "Ссылка на сервис" не заполнено".
Версия конфигурации: 0.9.0.0
Версия платформы: 8.3.24.1691
Скорее всего ошибка в том, что в модуле формы объекта справочника инт_Подписчики в обработчике события ПередЗаписьюНаСервере
идет обращение к несуществующему реквизиту объекта СсылкаНаСхему.

**Comment by ExpSPB** [comment]
Дополню: ошибки не было, так как до этого места в коде исполнение не доходило, так как не проходила проверка заполнения реквизитов.

**Comment by Segate-ekb** [comment]
Понял, повлиял переезд на новую схему хранения учетных данных пофикшу во вторник.

**Comment by Segate-ekb** [comment]
исправил
